djsite/djsite/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include



urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('posts.urls')),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

djsite/posts/urls.py
import profile

from django.contrib.messages import add_message
from django.urls import path
from .views import *

urlpatterns = [
    path('', index, name='index'),
    path('post/<int:post_id>/', show_post, name='post'),
    path('day/<int:day_id>/', show_day, name='day'),
    path('add_post/', add_post, name='add_post'),
    path('profile', profile, name='profile'),
    path('register', RegisterUser.as_view(), name='register'),
    path('login', LoginUser.as_view(), name='login'),
    path('logout', logout_user, name='logout'),
    path('obj/<int:obj_id>/', show_obj, name='obj'),
    path('review/<int:pk>/', AddMessage.as_view(), name='add_mes'),
    path('chats', chats, name='chats'),
    path('chat/<int:object_id>', show_chat, name='show_chat')

]

djsite/posts/models.py
from django.contrib.auth.models import User
from django.db import models
from django.urls import reverse


class Posts(models.Model):
    text = models.CharField(max_length=100)
    day = models.ForeignKey('Day', on_delete=models.CASCADE)
    date = models.DateField(null=True)
    object = models.ForeignKey('Object', on_delete=models.CASCADE)
    file = models.FileField(null=True, blank=True, upload_to='files/')

    def __str__(self):
        return self.text

    def get_absolute_url(self):
        return reverse('post', kwargs={'pk': self.pk})


class Day(models.Model):
    date = models.CharField(max_length=30)

    def __str__(self):
        return self.date

    def get_absolute_url(self):
        return reverse('day', kwargs={'pk': self.pk})


class Object(models.Model):
    name = models.CharField(max_length=100)

    def __str__(self):
        return self.name

    def get_absolute_url(self):
        return reverse('obj', kwargs={'pk': self.pk})


class Messages(models.Model):
    text = models.CharField(max_length=200)
    author = models.CharField(max_length=50, null=True)
    object = models.ForeignKey(Object, on_delete=models.CASCADE, null=True)

    def __str__(self):
        return f"{self.pk}, {self.text}"

    class Meta:
        verbose_name = 'Сообщение'
        verbose_name_plural = 'Сообщения'

djsite/posts/forms.py
from cProfile import label

from django import forms
from django.contrib.auth.forms import UserCreationForm, AuthenticationForm
from django.contrib.auth.models import User
from django.db.models import Model
from django.forms import ModelForm, TextInput, Select, DateInput, FileInput, Textarea
from django.http import request

from .models import *


class AddPostForm(ModelForm):
    day = forms.ModelChoiceField(queryset=Day.objects.all(), empty_label="День недели", widget=forms.Select(attrs={'class':'form-control'}))
    object = forms.ModelChoiceField(queryset=Object.objects.all(), empty_label="Предмет", widget=forms.Select(attrs={'class':'form-control'}))

    class Meta:
        model = Posts
        fields = ['text','day','object','date','file']

        widgets = {
            'text': Textarea(attrs={'class':'form-control', 'label':'Задание'}),
            'day': Select(attrs={'class': 'form-control', 'empty_label':'Предмет'}),
            'object': Select(attrs={'class':"form-control"}),
            'date': DateInput(attrs={'class': 'form-control','type':'date'}),
            'file': FileInput(attrs={'class': 'form-control', 'placeholder':'Прикрепите файл'})
        }


class RegisterUserForm(UserCreationForm):
    username = forms.CharField(max_length=100, label="Имя пользователя",widget=forms.TextInput(attrs={'class': 'form-control', 'placeholder':'miНейм'}))
    password1 = forms.CharField(max_length=100, label="Пароль", widget=forms.PasswordInput(attrs={'class': 'form-control','placeholder':'Пароль'}))
    password2 = forms.CharField(max_length=100, label="Повтор", widget=forms.PasswordInput(attrs={'class': 'form-control','placeholder':'Повтор пароля'}))

    class Meta:
        model = User
        fields = ('username','password1', 'password2')
        widgets = {
            'username': forms.TextInput(attrs={'class': 'form-control'}),
            'password1': forms.PasswordInput(attrs={'class': 'form-control'}),
            'password2': forms.PasswordInput(attrs={'class': 'form-control'}),
        }


class LoginUserForm(AuthenticationForm):
    username = forms.CharField(max_length=100, label='',widget=forms.TextInput(attrs={'class': 'form-control', 'placeholder': 'Ваше имя'}))
    password = forms.CharField(max_length=100, label='' ,widget=forms.PasswordInput(attrs={'class': 'form-control', 'placeholder': 'Пароль'}))


    class Meta:
        model = User
        fields = ('username','password1', 'password2')
        widgets = {
            'username': forms.TextInput(attrs={'class': 'form-control'}),
            'password': forms.PasswordInput(attrs={'class': 'form-control'}),
        }


class AddMessageForm(ModelForm):
    class Meta:
        model = Messages
        fields = ['author', 'text']

djsite/posts/views.py
from django.contrib.admin.helpers import AdminForm
from django.contrib.auth import login, logout
from django.contrib.auth.forms import UserCreationForm, AuthenticationForm
from django.contrib.auth.views import LoginView
from django.shortcuts import render, redirect
from django.template.context_processors import request
from django.urls import reverse_lazy
from django.views import View
from django.views.generic import CreateView, UpdateView, DetailView
from pyexpat import model

from .models import *
from .forms import AddPostForm, RegisterUserForm, LoginUserForm, AddMessageForm
from .utils import DataMixin


def index(request):
    posts = Posts.objects.all()
    return render(request, 'posts/index.html', {'posts': posts})


class DetailPost(DetailView):
    model = Posts
    template_name = 'posts/show.html'
    context_object_name = 'post'

def show_day(request, day_id):
    posts = Posts.objects.filter(day=day_id)
    return render(request, 'posts/show_day.html', {'posts':posts})


def show_post(request, post_id):
    post = Posts.objects.get(id=post_id)
    return render(request, 'posts/show.html', {'post':post})


def show_obj(request, obj_id):
    posts = Posts.objects.filter(object=obj_id)
    return render(request, 'posts/show_obj.html', {'posts':posts, 'object':object})


def add_post(request):
    if request.method == 'POST':
        form = AddPostForm(request.POST, request.FILES)
        if form.is_valid():
            form.save()
            return redirect('index')
    else:
        form = AddPostForm()
    return render(request, 'posts/add_page.html', {'form': form})


class RegisterUser(DataMixin, CreateView):
    form_class = RegisterUserForm
    template_name = 'posts/register.html'
    success_url = reverse_lazy('login')

    def get_context_data(self, *, object_list=None, **kwargs):
        context = super().get_context_data(**kwargs)
        c_def = self.get_user_context(title="Регистрация")
        return dict(list(context.items()) + list(c_def.items()))

    def form_valid(self, form):
        user = form.save()
        login(self.request, user)
        return redirect('index')


class LoginUser(DataMixin, LoginView):
    form_class = LoginUserForm
    template_name = 'posts/login.html'

    def get_context_data(self, *, object_list=None, **kwargs):
        context = super().get_context_data(**kwargs)
        c_def = self.get_user_context(title="Авторизация")
        return dict(list(context.items()) + list(c_def.items()))

    def get_success_url(self):
        return reverse_lazy('index')


def logout_user(request):
    logout(request)
    return redirect('login')


def profile(request):
    return render(request, 'posts/profile.html')


class PostsUpdateView(UpdateView):
    model = Posts
    template_name = 'posts/update_page.html'

    form_class = AddPostForm



class AddMessage(View):
    def post(self, request, pk):
        form = AddMessageForm(request.POST)
        if form.is_valid():
            form = form.save(commit=False)
            form.object_id = pk
            form.save()
        return redirect(f'/chat/{pk}')


def chats(request):
    return render(request, 'posts/chats.html')

def show_chat(request, object_id):
    object = Object.objects.get(pk=object_id)
    return render(request, 'posts/show_chat.html', {'object': object})

djsite/posts/templates/posts/add_page.html
{% extends 'posts/base.html' %}
{% block content %}

    <form method="POST" action="{% url 'add_post' %}" enctype="multipart/form-data">
        {% csrf_token %}
        {{ form.text }}
        {{ form.day }}
        {{ form.date }}
        {{ form.object }}
        {{ form.file }}
        <button type="submit" class="btn btn-primary">Submit</button>
    </form>

{% endblock content %}

djsite/posts/templates/posts/base.html
{% load static %}
{% load posts_tags %}
<html>
  <head>
      <meta name="viewport" content="width=device-width, initial-scale=1">
      <link rel="stylesheet" type="text/css" href="{% static 'posts/css/styles.css' %}">
    <title>{% block title %}{% endblock title %}</title>
       <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0-alpha1/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-GLhlTQ8iRABdZLl6O3oVMWSktQOp6b7In1Zl3/Jr59b6EGGoI1aFkw7cmDA6j6gD" crossorigin="anonymous">
  </head>
  <body>
    <nav class="navbar navbar-expand-xl navbar-dark bg-black nav-fixed" aria-label="Sixth navbar example">
    <div class="container-fluid">
        <a class="navbar-brand" href="/">NetClass</a>
        {% if request.user.is_authenticated %}
        <a class="navbar-brand">{{ user.username }}</a>
        <a class="navbar-brand" href="{% url 'logout' %}">Выйти</a>
        <a class="navbar-brand" href="{% url 'add_post' %}">
            <h1>+</h1>
        </a>
        {% else %}
        <a class="navbar-brand" href="{% url 'login' %}">Войти</a>
        {% endif %}
        <a class="navbar-brand" href="{% url 'chats' %}">Чаты</a>
      <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarsExample06"  aria-expanded="false">
        <span class="navbar-toggler-icon"></span>
      </button>

      <div class="navbar-collapse collapse" id="navbarsExample06" style="">
        <ul class="navbar-nav me-auto mb-2 mb-xl-0">
            <li class="nav-item"><h2><a class="nav-link active">По предметам</a></h2></li>
            {% get_obj as objects %}
            {% for object in objects %}
            {% if object.posts_set.exists %}
                <li class="nav-item">
                    <a class="nav-link active" aria-current="page" href="{% url 'obj' object.pk %}">{{ object }}</a>
                </li>
            {% else %}
            {% endif %}
            {% endfor %}
            <li class="nav-item"><h2><a class="nav-link active">По дням</a></h2></li>
            {% get_days as days %}
            {% for d in days %}
                {% if d.posts_set.exists %}<li class="nav-item">
                    <a class="nav-link active" href="{% url 'day' d.pk %}">{{ d }}</a>
                </li>
                {% else %}
                {% endif %}
            {% endfor %}
        </ul>
      </div>
    </div>
  </nav>
    <div class="wrapper">
      {% block content %}

      {% endblock content %}
    </div>

    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0-alpha1/dist/js/bootstrap.bundle.min.js" integrity="sha384-w76AqPfDkMBDXo30jS1Sgez6pr3x5MlQ1ZAGC+nuZB+EYdgRZgiwxhTBTkF7CXvN" crossorigin="anonymous"></script>
  </body>
    <script>


    </script>
</html>

djsite/posts/templates/posts/chats.html
{% extends 'posts/base.html' %}
{% load posts_tags %}
{% block content %}
    {% get_obj as objects %}
    {% for object in objects %}
                    <a class="btn btn-primary" aria-current="page" href="{% url 'show_chat' object.id %}">{{ object }}</a><br>
    {% endfor %}
{% endblock content %}

djsite/posts/templates/posts/index.html
{% extends 'posts/base.html' %}
{% load static %}
{% load posts_tags %}
    {% block content %}
        <div class="posts">
            {% for p in posts %}
                <div class="post">
                     <h2>По {{ p.object }}</h2>
                    <h3 class="text">{{ p.text }}</h3>
                    <p class="day">На {{ p.day }}  {{ p.date }}</p>
                    {% if p.file %}
                    <div class="file"><a href="{{ p.file.url }}">Файл</a><img src="{% static 'posts/img/screpka.png' %}" width="40"></div>
                    {% endif %}
                    <a class="read-post" href="{% url 'post' p.pk %}">Читать</a>

                </div>
            {% endfor %}
        </div>
    {% endblock content %}

djsite/posts/templates/posts/login.html
{% extends 'posts/base.html' %}
{% block content %}
<h1 class="center-title">Войти как учитель</h1>
<form  method="post">
    {% csrf_token %}
    {{ form.as_p}}
    <button type="submit" class="btn btn-primary btn-reg">Войти</button>
</form>
{% endblock content %}

djsite/posts/templates/posts/register.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <link rel="stylesheet" type="text/css" href="{% static 'posts/css/styles.css' %}">
    <title>Title</title>
     <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0-alpha1/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-GLhlTQ8iRABdZLl6O3oVMWSktQOp6b7In1Zl3/Jr59b6EGGoI1aFkw7cmDA6j6gD" crossorigin="anonymous">
</head>
<body>

<form class="reg" method="post">
    <h1>Регистрация</h1>
    {% csrf_token %}
    {{ form.username }}
    {{ form.password1 }}
    {{ form.password2 }}
    <button type="submit" class="btn btn-primary">Зарегистрироваться</button>
</form>
</body>
</html>

djsite/posts/templates/posts/show.html
{% extends 'posts/base.html' %}
{% load static %}
{% block content %}
        <div class="posts">
                <div class="post">
                    <h2>{{ post.object }}</h2>
                    <h4 class="text">{{ post.text }}</h4>
                    <p class="day">На {{ post.day }}  {{ post.date }}</p>
                    <a class="read-post">Читать</a>
                    {% if post.file %}
                    <div class="file"><a href="{{ post.file.url }}">Файл</a><img src="{% static 'posts/img/screpka.png' %}" width="40"></div>
                    {% endif %}
                </div>
        </div>

{% endblock content %}

djsite/posts/templates/posts/show_chat.html
{% extends 'posts/base.html' %}
{% load posts_tags %}
{% block content %}
<div class="form-message">
  <form method="post" action="{% url 'add_mes' object.id %}">
      {% csrf_token %}
      текст:
      <input name="text" class="form-control"><br>
      от кого :
      <input name="author" class="form-control"> <br>
      <button type="submit" class="btn btn-Success">Отправить</button>
  </form>
</div>
{% get_mes as messages %}
<div class="messages">
    {% for m in object.messages_set.all %}
        {{ m.text }}<br>
      от  {{ m.author }}<br><br>
    {% endfor %}
</div>
{% endblock content %}

djsite/posts/templates/posts/show_day.html
{% extends 'posts/index.html' %}
        <div class="objects">
            {% for object in objects %}
                <a class="btn btn-outline-primary" href="{% url 'obj' object.pk %}">{{ object }}</a>
            {% endfor %}
        </div>

djsite/posts/templates/posts/show_obj.html
{% extends 'posts/base.html' %}
P% load posts_tags %}
{% load static %}
{% block content %}
        <div class="post">
                {% for p in posts %}
                        <div class="post">
                     <h2>По {{ p.object }}</h2>
                    <h3 class="text">{{ p.text }}</h3>
                    <p class="day">На {{ p.day }}  {{ p.date }}</p>

                    {% if p.file %}
                    <div class="file"><a href="{{ p.file.url }}">Файл</a><img src="{% static 'posts/img/screpka.png' %}" width="40"></div>
                    {% endif %}
                    <a class="read-post" href="{% url 'post' p.pk %}">Читать</a>
                </div>
                {% endfor %}

        </div>
{% endblock content %}